name: colorful_log
description: A Dart package for logging messages with colorful console outputs for enhanced readability and debugging.
version: 1.0.0
homepage: https://github.com/Moein-dev/colorful_log


environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
